sudo: false
language: node_js

before_install:
  - npm install -g npm

before_script:
  - npm run download-selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start && sleep 1

script:
  - npm run travis
  - npm run integration
  - cat test-integration/nohup.out

node_js:
  - "0.10"
  - "0.12"
  - "iojs"

matrix:
  allow_failures:
    - node_js: "0.12"
    - node_js: "iojs"

addons:
  - firefox: "35.0"
